In [7]:
import numpy as np

In [8]:
def get_new_matrix(n):
    # A = np.round(np.random.randn(n,n), 2)
    # X = np.round(np.random.randn(n), 2)
    # B = np.round(np.dot(A, X), 2)
    # return A, B, X
    A = 

In [9]:
def get_full_matrix(A, B):
    return np.insert(A, np.shape(A)[1], B, axis = 1)

In [10]:
def forward(A):
    n = np.shape(A)[0]
    for i in range(n):
        main_index = np.argmax(np.abs(A[i:, i])) + i
        C = np.copy(A[i])
        A[i] = np.copy(A[main_index])
        A[main_index] = np.copy(C)
        A[i] /= A[i, i]
        for j in range(i+1, n):
            A[j] -= A[i]*A[j, i]
    return np.round(A, 2)

In [11]:
def backward(A):
    n = np.shape(A)[0]
    for i in range(1, n):                                           
        for j in range(1, n):                                       
            A[n-i-j] -= A[n-i]*A[n-i-j, n-i]                       
    return np.round(A, 2)

In [12]:
A, B, X = get_new_matrix(4)
print('Получена матрица A:')
print(f'{A}, вектор-столбец B: {B} и вектор-столбец X: {X}')
D = get_full_matrix(A, B)
print('Присоединённая матрица D:')
print(D)
print('Прямой проход метода Гаусса:')
print(forward(D))
print('Обратный проход метода Гаусса:')
print(backward(D))
print('Сверяем последний столбец матрицы с вектором Х:')
print(np.round(np.transpose(D[0:, np.shape(D)[1] - 1]), 2))
print(X)

Получена матрица A:
[[ 2.19  2.3  -0.31 -0.29]
 [ 0.    0.14  0.24  0.47]
 [ 0.02 -0.56  0.93  1.6 ]
 [ 1.62  0.54  2.07 -0.31]], вектор-столбец B: [1.42 0.82 3.02 5.64] и вектор-столбец X: [1.   0.03 2.04 0.7 ]
Присоединённая матрица D:
[[ 2.19  2.3  -0.31 -0.29  1.42]
 [ 0.    0.14  0.24  0.47  0.82]
 [ 0.02 -0.56  0.93  1.6   3.02]
 [ 1.62  0.54  2.07 -0.31  5.64]]
Прямой проход метода Гаусса:
[[ 1.    1.05 -0.14 -0.13  0.65]
 [-0.    1.   -1.98  0.08 -3.95]
 [ 0.    0.    1.    0.89  2.66]
 [ 0.    0.    0.    1.    0.7 ]]
Обратный проход метода Гаусса:
[[1.   0.   0.   0.   1.01]
 [0.   1.   0.   0.   0.02]
 [0.   0.   1.   0.   2.04]
 [0.   0.   0.   1.   0.7 ]]
Сверяем последний столбец матрицы с вектором Х:
[1.01 0.02 2.04 0.7 ]
[1.   0.03 2.04 0.7 ]
